version: '3'

services: # Указываем сервисы которые будут задействованы
  django: # Имя первого сервиса
    build: . # билд указывает что мы будем вытягивать все настройки из нашего докерфайла, и указываем путь в виде точки, так как фаил находится в той же папке
    container_name: Django # даем имя контейнеру
    command: python manage.py runserver 0.0.0.0:8000 # команды выполняются при построении сервиса. В данном случае мы запускаем локальный сервер который уже установлен в джанго. Менедж.ру это специальный файл в питоне к которому мы должны обратиться прежде чем вызвать какую либо команду, в нашем случае мы вызываем команду рансервер, задаем адрес и порт что значит что он локальный
    volumes:
      - .:/usr/src/app
    ports: # Указываем порты по которым мы будем подключаться. Указываем что здесь на локальной машине порт 8000 и указываем порт к которому будем подключаться. мы указывали его выше в строке команд, где он тоже 8000
      - "8000:8000"
    depends_on: # тут мы указываем что данный сервис, в данном случае джанго, он будет зависеть от такого сервиа который мы указываем ниже.
      - pgdb

  pgdb:
    image: postgres # образ база данных
    environment: # переменные которые будут нужны к подключению самой базе данных
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb # название контейнера
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

volumes:
  pgdbdata: null